### ISSUE TITLE
ri => "Nothing known about ..."

### ISSUE THREAD

**Issue by vais** [oneclick/rubyinstaller2#119]
RubyInstaller ships with HTML docs but not RI docs, and the `rdoc-data` [gem](https://github.com/rdoc/rdoc-data) support currently stops at Ruby 2.3.

Therefore `ri` cannot be used to get help with corelib and stdlib classes for the more recent Rubies.

What's the best way to rectify this issue? Ship RI docs with RubyInstaller? Update `rdoc-data` gem?

**Comment by larskanis** [comment]
I tried to ship RI docs with RubyInstaller2 but decided against it, because:
1. in contrast to HTML, RI docs are stored as one file per method, which Windows doesn't handle well
2. it enlarged the installer by around 4MB
3. it slowed installation down by around factor 3

Given that we now ship the much bigger DevKit within the installer, we could re-consider this decision. Maybe ship RI docs as a selectable component within the DevKit installer only?

**Comment by vais** [comment]
I ended up copying the `share/ri/2.4.0/system` directory from the Ruby installation on my Mac (installed with rbenv) to the Ruby 2.4.0 installation on my Windows machine, and `ri` is working for me again.

Playing with Elixir (which has docs integrated right into its REPL) made me remember that at one point Ruby too had really nice docs available from the command line, without having to Google things.

Of course, as soon as I wrote the sentence above, I remembered that Ruby's `pry` has docs built in as well. Looks like it has its own database inside the [pry-doc plugin](https://github.com/pry/pry-doc) which I guess is not compatible with `ri`...

I think it's worth having `ri` docs available as an install-time option and/or as a separate download. For what it's worth, rbenv installs `ri` docs by default :)
