### ISSUE TITLE
Ruby v2.6.2

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [oneclick/rubyinstaller2#147]
I can see v[2.6.2](https://www.ruby-lang.org/en/news/2019/03/13/ruby-2-6-2-released/) ready for platforms other than Windows.
Is it too soon for expectations (on Windows)?

**Comment by PauloFrancaLacerda** [comment]
Installed and enjoyed.
Asciidoctor says "thank you!"
![ruby-262](https://user-images.githubusercontent.com/17791112/56231934-ff1ba800-6055-11e9-82ca-94c62b15473b.png)

**Comment by larskanis** [comment]
Sorry for the delay regarding the latest releases! I was simply too busy at work and with the [EU copyright](http://savetheinternet.info/) to track down a difficult segfault with ruby-2.5.5 on Windows, when built with the latest gcc version. Not knowing the root cause delayed all the releases. I'll try to open a ticket for this issue on http://bugs.ruby-lang.org soon.

I hope everything is running smooth now!

**Comment by PauloFrancaLacerda** [comment]
> I hope everything is running smooth now!

Surely "running smooth". v2.6.3 so quickly was a very nice surprise.  :)

**Comment by larskanis** [comment]
Just for your information: I'll release rubyinstaller-2.6.4 etc. in the next days, when I got a renewed developer certificate from Certum to sign the release binaries.
