### ISSUE TITLE
Help with configuration issues

### ISSUE THREAD

**Issue by Vm900** [oneclick/rubyinstaller2#170]
Hi,
Just recently used the Ruby+Devkit 2.6.5 (x64) installer.Everything installed properly but when i attempt
attempted to run ruby inside msys2 the program is not available(not found).
Help thanks

**Comment by larskanis** [comment]
Please use the issue template the next time, so that others can better understand what you're doing and what fails for you!

You're speaking about msys2 console? It sets it's own `PATH` environment variable and disables programs that are in the path in cmd or powershell. You can add ruby per
```sh
export PATH=/C/Ruby26-x64/bin/:$PATH
```
or for instance by adding this line to your `~/.bashrc`. But please note, although RubyInstaller works to some extend in bash, but isn't fully supported so far (only cmd and powershell are).

**Comment by Vm900** [comment]
Aah paths.Thanks a  million
