### ISSUE TITLE
How to go on with RubyInstaller-x86?

### ISSUE THREAD

**Issue by larskanis** [oneclick/rubyinstaller2#185]
Regarding the future of the x86 build I'm somewhat uncertain. I think about these two options:
1. Using a more and more outdated i686 MSYS2 toolchain.
2. Switch to the x86_64 MSYS2 toolchain, but stay at i686 for MINGW and Ruby.

Option 1 doesn't need much work, but will probably lead to some incompatibilities in the future with `pacman` or similar and bugs in MSYS2 tools will not be fixed.

Option 2 needs some changes in the RubyInstaller build scripts and more efforts in the installer to migrate `msys32` installations to `msys64`. Furthermore it adds the requirement for a x64 capable Windows to RubyInstaller-x86.

On the one hand RubyInstaller-x86 releases will be stopped some day in the future because they are no longer supported upstream and most people don't case about it. But on the other hand the download counts are still 10% to 15% for the x86 version.

I for one still have a single use case requiring a 32 bit DLL and so RubyInstaller-x86. Both above options would work for me, but RubyInstaller-x64 wouldn't.

**Comment by larskanis** [comment]
For now we go with option 1. This required [some](https://github.com/oneclick/rubyinstaller2/commit/2ed495710bae637f8985acbce7a02116088d3d14) [fixes](https://github.com/oneclick/rubyinstaller2/commit/cf4caeb0287660ce51456731ecb9c5463654fe48) in RubyInstaller-2.7.2, but worked in the end.

**Comment by rubyFeedback** [comment]
I'd recommend to make it available for a bit longer. Sooner or later the number of users
will dwindle anyway, but I think that a few old computers out there may still be using 
32 bit, so I don't think you are with the only use case here.

I myself switched to 64 bit so I don't really need that option. But some years ago, I 
think it made perfect sense to have 32 bit ruby as well. Some people are slower
in their transition pathway. It took me a few years before I abandoned syck in
favour of psych by the way. Now I am using psych exclusively (reason I could
not switch was due to unicode, but after emoji support, I realized that you can
use them for commandline stuff + RGB colours, and that made me actually
transition).

**Comment by mohits** [comment]
Hi @larskanis - since this is a discussion with no updates for almost 1 year, do you think we can close this?

**Comment by larskanis** [comment]
I still have some computers with a 32 bit Windows running RubyInstaller-x86 and with the patches above it's running quite well. So until there are major issues with it, I'll continue to support the 32 bit version.
