### ISSUE TITLE
Receive Error message when Install Jekyll

### ISSUE THREAD

**Issue by wongyah** [oneclick/rubyinstaller2#207]
## What problems are you experiencing?

![image](https://user-images.githubusercontent.com/38174537/105007705-46c53400-5a73-11eb-9555-a1f865561711.png)

## Steps to reproduce

1. Download the "Ruby+Devkit 2.7.2-1 (x64)", and run the installer with default settings (except the installation folder).
2. Run the command ```ridk install```.
3. Run the command ```gem install jekyll bundler```, received error message above.

## What's the output from `ridk version`?

![image](https://user-images.githubusercontent.com/38174537/105008042-b3403300-5a73-11eb-94da-c1190b199d59.png)

**Comment by larskanis** [comment]
The first picture shows, that there is a connectivity issue while downloading Jekyll. Maybe some firewall or proxy issue?

The error with `ridk version` is unrelated to Jekyll. It is due to an encoding issue in this command. I'll fix it in the next release, but it shouldn't hinder you to use Jekyll in any way, when the connectivity issue is solved.

**Comment by wongyah** [comment]
I am a Chinese user. The website may be blocked in China.

Here is the solution with which I have installed jekyll 👇👇👇:

https://github.com/juthilo/run-jekyll-on-windows/issues/34#issuecomment-606421543
