### ISSUE TITLE
https://rubyinstaller.org/ is outdated

### ISSUE THREAD

**Issue by net1957** [oneclick/rubyinstaller2#237]
## What problems are you experiencing?
https://rubyinstaller.org/ page is outdated

## Steps to reproduce
Goto https://rubyinstaller.org/

## What's the output from `ridk version`?
Not relevant

The home page of RubyInstaller show latest news dated 2020-12-27.
But you are now 2 releases later.

It's not a big issue but we need one more click on Download to check new release.

New users can understand it's not well maintained. And for sure it's not true!!

Regards

**Comment by shaunmabbs** [comment]
@larskanis I have come up with the following draft news posts for 3.0.1 & 3.0.2 for your review. Maybe you could add your comments here for releases & I could create the posts & pull requests to master.

**3.0.2 Release** 
RubyInstaller-3.0.2-1 has been released!
These are maintenance releases with bug and security fixes.
See the [ruby-3.0.2 release post](https://www.ruby-lang.org/en/news/2021/07/07/ruby-3-0-2-released/) for more details.

Enabled ruby to support path length of more than 260 characters. See commit [829ab9d](https://github.com/oneclick/rubyinstaller2/commit/829ab9d9798d180655b6b336797b1087bfa82f5c)
Added racc, rbs and typeprof executables to the /bin folder. See [#231](https://github.com/oneclick/rubyinstaller2/issues/231)

Please note, that some gems are not yet compatible with Ruby-3.0 on Windows.
In this case you might stay on 2.7 until 3.0 is well supported.

A previous RubyInstaller-2.6.x or 2.7.x installation <b>should not</b> be updated by installing RubyInstaller-3.0.x into the same directory.
This is because gems with C extensions are not compatible between ruby-2.7 and 3.0.
It's best to use a new directory for 3.0.x as proposed by the installer.

All binaries are available in the [Download section]({{ "/downloads/" | relative_url }})!

**3.0.1 Release** 
RubyInstaller-3.0.1-1 has been released!
These are maintenance releases with bug and security fixes.
See the [ruby-3.0.1 release post](https://www.ruby-lang.org/en/news/2021/04/05/ruby-3-0-1-released/) for more details.

Added more environment variables needed for configure scripts: MSYSTEM_PREFIX, MSYSTEM_CARCH, MSYSTEM_CHOST, MINGW_CHOST, MINGW_PREFIX

Please note, that some gems are not yet compatible with Ruby-3.0 on Windows.
In this case you might stay on 2.7 until 3.0 is well supported.

A previous RubyInstaller-2.6.x or 2.7.x installation <b>should not</b> be updated by installing RubyInstaller-3.0.x into the same directory.
This is because gems with C extensions are not compatible between ruby-2.7 and 3.0.
It's best to use a new directory for 3.0.x as proposed by the installer.

All binaries are available in the [Download section]({{ "/downloads/" | relative_url }})!

**Comment by larskanis** [comment]
Looks good! I think you can use the release date as the date of the post.

**Comment by larskanis** [comment]
Thank you @shaunmabbs  for writing the release post!
