### ISSUE TITLE
gem install jekyll bundler throwing error

### ISSUE THREAD

**Issue by sathiyasheelan-T** [oneclick/rubyinstaller2#293]
## What problems are you experiencing?
while installing "gem install jekyll bundler" I am getting the following Error

Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 -r ./siteconf20220717
-3852-lfmb4i.rb extconf.rb
creating Makefile

current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
make DESTDIR\= clean

current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
make DESTDIR\=
compiling ./libsass/src/ast.cpp
{standard input}: Assembler messages:
{standard input}:7466: Error: junk `:' after expression
make: *** [Makefile:238: ast.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-
2.4.0 for inspection.
Results logged to C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.
1.0/sassc-2.4.0/gem_make.out
Successfully installed bundler-2.3.18
Parsing documentation for bundler-2.3.18
Done installing documentation for bundler after 0 seconds
1 gem installed

## Steps to reproduce
Its fresh installation

## What's the output from `ridk version`?
ruby:
  path: C:/Ruby31-x64
  version: 3.1.2
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.2-1
  git_commit: 17502f9
msys2:
  path: C:\Ruby31-x64\msys64
cc: gcc (Rev10, Built by MSYS2 project) 11.2.0
sh: GNU bash, version 5.1.16(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.1.7601]

**Comment by mohits** [comment]
Hi @sathiyasheelan-T 

Could you please share the following information (since I'm unable to replicate this on my Windows PC).

I notice that you're using Windows `Version 6.1.7601` which identifies as Windows 7 or Windows Server 2008 R2. Could you confirm which version of Windows you are using?

There is a possibility that it's an issue with using Windows 7/ 2008 but I don't have access to a machine here to be able to check easily.

Maybe, someone else has an opinion after we hear from you.

For reference, this is what I have:

```
$ ridk version
---
ruby:
  path: C:/Ruby31-x64
  version: 3.1.1
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.1-1
  git_commit: d9d39f1
msys2:
  path: C:\Ruby31-x64\msys64
cc: gcc (Rev9, Built by MSYS2 project) 11.2.0
sh: GNU bash, version 5.1.8(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19044.1826]
```

(Yours is 3.1.2-1 and mine is 3.1.1-1 but the rest is pretty much the same). Also, when I try to just install `sassc` which is the gem you struggled with, this is what I get (basically no issues).

```
$ gem install jekyll
Fetching sassc-2.4.0.gem
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed sassc-2.4.0
Successfully installed jekyll-4.2.2
Parsing documentation for sassc-2.4.0
Installing ri documentation for sassc-2.4.0
Parsing documentation for jekyll-4.2.2
Done installing documentation for sassc, jekyll after 5 seconds
2 gems installed
```

**Comment by mohits** [comment]
hi @sathiyasheelan-T - there was no response to my previous message. I would like to close this issue if things are working fine for you. If we don't hear from you, I will close it next week. Thanks!
