### ISSUE TITLE
system calls that pipe to /dev/null fail with "The system cannot find the path specified."

### ISSUE THREAD

**Issue by gfody** [oneclick/rubyinstaller2#323]
I'm not sure if this is actually a rubyinstaller or msys problem, as you _could_ code specifically for windows with ` > nul` instead of ` > /dev/null` but ideally this would work as-is..

## What problems are you experiencing?
Working with ruby code that makes a lot of system calls with the output piped to /dev/null on Windows it's executing something like:
```sh
sh -c echo asdf > /dev/null
The system cannot find the path specified.
```
as a workaround I can create a file at `C:\dev\null` but it seems like there could be a better way?

## Steps to reproduce
```ruby
irb(main):001:0> `echo asdf > /dev/null`
The system cannot find the path specified.
=> ""
irb(main):002:0> system("echo asdf > /dev/null")
The system cannot find the path specified.
=> false
```

## What's the output from `ridk version`?
I'm using vanilla msys2 and installed ruby from `ci.ri2/mingw-w64-x86_64-ruby27 2.7.7-1`

**Comment by larskanis** [comment]
`/dev/null` is only valid in an MSYS2 application. But all MINGW applications are native Windows, so that only `NUL` is valid.  Similar, if you shell out from ruby, the `echo` command of `CMD` is executed, which is a native Windows application as well.

In ruby there is a constant for the null device of the running platform. It is `File::NULL` or so. Can't test right now...

**Comment by gfody** [comment]
ah that make sense, so for this project I should try an msys build of ruby instead of mingw (or I can try to make the code more portable w/File::NULL) - thanks!
