### ISSUE TITLE
MSYS2 OpenSSL changed from 'etc/ssl' to 'bin/etc/ssl'

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2#337]
Lars,

Another fun MSYS2 change.  See https://github.com/msys2/MINGW-packages/pull/16141.

Or, the following have all changed:
```
OpenSSL::X509::DEFAULT_CERT_FILE
OpenSSL::X509::DEFAULT_CERT_DIR
OpenSSL::Config::DEFAULT_CONFIG_FILE
```

**Comment by lazka** [comment]
https://github.com/msys2/MINGW-packages/pull/16141 wasn't supposed to change anything for the common case. Do you have any idea why this affects you?

**Comment by MSP-Greg** [comment]
> for the common case

The MSYS2 dll's included with Ruby are located in `bin/ruby_builtin_dlls`, so they are not accessible via PATH.  This was done to alleviate problems with all the various Windows 'apps' that may share dll names.

**Comment by lazka** [comment]
uh, I see. I don't have a good idea on how to make both cases work :(

**Comment by MSP-Greg** [comment]
Other than removing a trialing `bin` (or something similar) from the folder, I also don't see a good way of fixing it.

**Comment by larskanis** [comment]
Thank you @MSP-Greg and @lazka for investigating this issue. I dithered between using a forked build script and accepting the new path, but decided to do the latter. It is a user visible change, since some users place their own certificates at the openssl path. They have to move it now. I hope it will be the last path change for the foresight future!

**Comment by MSP-Greg** [comment]
> I hope it will be the last path change for the foresight future

Strongly agree...
