### ISSUE TITLE
Encoding.default_external should reflect OS codepage

### ISSUE THREAD

**Issue by JunichiIto** [oneclick/rubyinstaller2#37]
I installed Ruby 2.4.1 with rubyinstaller-2.4.1-1rc2-x64.exe and I am using Japanese Windows 10:

<img width="1108" alt="screen shot 2017-04-30 at 8 12 26" src="https://cloud.githubusercontent.com/assets/1148320/25559790/f2e69ac6-2d7c-11e7-8c35-485f28376ae1.png">

The [CHANGELOG](https://github.com/oneclick/rubyinstaller2/blob/master/CHANGELOG.md) says "Encoding.default_external is now UTF-8 — no longer ancient cpXYZ encoding when reading files.", but this is not ideal for Japanese users because Japanese characters are garbled in irb:

```
c:\>irb
irb(main):001:0> a='あいうえお'
=> "\x{82A0}\x{82A2}\x{82A4}\x{82A6}\x{82A8}"
irb(main):002:0> Encoding.default_external
=> #<Encoding:UTF-8>
```

I had to specify codepage with "-E" option:

```
c:\>irb -E CP932
irb(main):001:0> a='あいうえお'
=> "あいうえお"
irb(main):002:0> Encoding.default_external
=> #<Encoding:Windows-31J>
```

So I think Encoding.default_external should reflect OS codepage like before.

**Comment by JunichiIto** [comment]
P.S.

You might have noticed this issue in the following thread:

[Feature \#13488: Set Encoding\.default\_external to UTF\-8 on Windows \- Ruby trunk \- Ruby Issue Tracking System](https://bugs.ruby-lang.org/issues/13488).

**Comment by Iristyle** [comment]
@JunichiIto I agree and filed a very similar issue report in #38 (before I noticed you had filed the same report).

I believe the UTF-8 patch should be reverted.

**Comment by larskanis** [comment]
@JunichiIto After installing Japanese language options in Windows 10, I'm able to set "Japanese" as default for non Unicode programs in the Windows settings. This enables cp932 alias Windows-31J in my windows console (`chcp 932` did not work initially, but now).

However even after switching to cp932 I can not reproduce your issue:
```sh
$ irb -Eutf-8
irb(main):011:0> "\u00E4\u0416\u3042"
=> "äЖあ"
irb(main):012:0>

$ irb -Ecp932
irb(main):001:0> "\u00E4\u0416\u3042"
=> "\u00E4\u0416\u3042"
irb(main):002:0>
```

In fact it's roughly the opposite to your result.
When using the Windows defaults for western Europe, it's equally: When ruby runs with `cp850`, strings are printed as `"\x84"` instead of `"ä"`. But it works with `-Eutf-8`.

**Comment by JunichiIto** [comment]
@larskanis Thank you for your reply. I will check it later.

**Comment by kubo** [comment]
As far as I checked, if a string encoding is different with the default external encoding, the string is printed with `"\x..."` or `"\u..."`.
The encoding of string literals in the @JunichiIto's comment is cp932(Windows-31J). On the other hand, that in the @larskanis's comment is utf-8 due to unicode escape sequences.

```shell
C:\>chcp 932
現在のコード ページ: 932

C:\bin>irb
irb(main):001:0> Encoding.default_external
=> #<Encoding:UTF-8>
irb(main):002:0> __ENCODING__ # This depends on the code page when `-E` isn't specified.
=> #<Encoding:Windows-31J>
irb(main):003:0> "\x82\xA0".encoding # "\x82\xA0" is code point of 'あ' in cp932. Its encoding is same with __ENCODING__
=> #<Encoding:Windows-31J>
irb(main):004:0> "\x82\xA0" # when the string encoding != Encoding.default_external
=> "\x{82A0}"
irb(main):005:0> "\u3042".encoding
=> #<Encoding:UTF-8>
irb(main):006:0> "\u3042" # when the string encoding == Encoding.default_external
=> "あ"
irb(main):007:0> "\x82\xA0".encode(Encoding.default_external)
=> "あ"

C:\>irb -E cp932
irb(main):001:0> Encoding.default_external
=> #<Encoding:Windows-31J>
irb(main):002:0> __ENCODING__ # the encoding specified by '-E' (The default depends on the code page.)
=> #<Encoding:Windows-31J>
irb(main):003:0> "\x82\xA0".encoding # same with __ENCODING__
=> #<Encoding:Windows-31J>
irb(main):004:0> "\x82\xA0" # when the string encoding == Encoding.default_external
=> "あ"
irb(main):005:0> "\u3042".encoding
=> #<Encoding:UTF-8>
irb(main):006:0> "\u3042" # when the string encoding != Encoding.default_external
=> "\u3042"
irb(main):007:0> "\u3042".encode(Encoding.default_external)
=> "あ"
```

**Comment by kubo** [comment]
> As far as I checked, if a string encoding is different with the default external encoding, the string is printed with "\x..." or "\u...".

It isn't correct. I did similar procedure with the previous comment for cp850. I got escape sequences even though the string encoding is same with the default external encoding.
I'm using rubyinstaller-2.4.1-1rc2-x64 on Japanese Windows (Windows 10 Pro version 1703).

```shell
C:\>chcp 850
Active code page: 850

C:\>irb
irb(main):001:0> Encoding.default_external
=> #<Encoding:UTF-8>
irb(main):002:0> __ENCODING__
=> #<Encoding:CP850>
irb(main):003:0> "\x84".encoding
=> #<Encoding:CP850>
irb(main):004:0> "\x84"
=> "\x84"
irb(main):005:0> "\u00e4".encoding
=> #<Encoding:UTF-8>
irb(main):006:0> "\u00e4"
=> "ä"
irb(main):007:0> "\x84".encode(Encoding.default_external)
=> "ä"
irb(main):008:0> exit

C:\>irb -E cp850
irb(main):001:0> Encoding.default_external
=> #<Encoding:CP850>
irb(main):002:0> __ENCODING__
=> #<Encoding:CP850>
irb(main):003:0> "\x84".encoding
=> #<Encoding:CP850>
irb(main):004:0> "\x84" # I guessed that this printed "ä" because the encoding == Encoding.default_external but not.
=> "\x84"
irb(main):005:0> "\u00e4".encoding
=> #<Encoding:UTF-8>
irb(main):006:0> "\u00e4"
=> "\u00E4"
irb(main):007:0> "\u00e4".encode(Encoding.default_external)
=> "\x84"
irb(main):008:0>
```

**Comment by larskanis** [comment]
@kubo Thank you for posting your results! This helps understanding the issue. However be careful with irb - it uses a different script encoding (`__ENCODING__`) compared to ruby files. This is because irb uses `eval` and `eval` sets `__ENCODING__` based on the parameter string:
```ruby
eval("__ENCODING__".encode("cp852"))  # => #<Encoding:CP852>
```

All in all this says me, that the issue is most likely only a [rb-readline](https://github.com/ConnorAtherton/rb-readline) issue. rb-readline works on locale codepages on windows currently and passes cpXYZ encoded strings to irb. It's probably best to port it to the Unicode capable API of the Windows console (say [ReadConsoleInputW](https://msdn.microsoft.com/de-de/library/windows/desktop/ms684961(v=vs.85).aspx) and so on) and use UTF-8 there as well. This should solve the current issues with irb. I'll check this (but it could take some days...).

**Comment by JunichiIto** [comment]
@kubo @larskanis Thank you for your information. I am mainly using Mac and do not know much about Windows, so as of now I am not able to give more useful information.

**Comment by JunichiIto** [comment]
With https://github.com/oneclick/rubyinstaller2/releases/download/2.4.1-1/rubyinstaller-2.4.1-1-x64.exe , I confirmed Encoding.default_external is Windows-31J in irb. Thank you for all your support.
