### ISSUE TITLE
Decouple MSYS2/MinGW from ruby?

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2#59]
In previous discussions here or even in old RI issues, I may have hinted at this issue.

Recently I've been building & testing ruby_2_3 & ruby_2_4 stable builds with rubygems and all gems updated (info [here](https://msp-greg.github.io/file.mingw_builds.html)).  I did this to check whether there might be commits to trunk that should be backported but haven't been.  Anyway, the work clarified the isssue somewhat...

I think consideration should be given to using the MSYS2/MinGW environment (MSYS2) only for building/compiling/installing, and adding code to copy package dll's to  `bin\ruby_builtin_dlls` (and other locations like `lib` for OpenSSL) as required.

Your may be thinking about something similar; I won't go into the reasons, but I'd be happy to.

By doing something like this, it would allow multiple ruby install's to remain independent, allow users to use different package versions for testing, gem development, etc.  Someone could even create a 'Rails' ruby install package with all the required dll's and maybe even gems (not suggesting we do it).

In some respects, it may help with 'dll hell' issues that I think are very possible.  It won't solve all of them, but it might be a strong step in the right direction.

The attached code is a simple POC for getting dll info from a package.  You may already have the same.  With a few changes, it could move/copy dll's from MSYS2 to the ruby install.  Used with `spec.metadata["msys2_mingw_dependencies"]`, it should be relatively easy to implement, most difficult part being how to parse/change the manifest.

BTW, thanks for the PR in OpenSSL, I keep forgetting about metadata, as I've come across some gems it should be added to.  Thanks again for all your work.

[pacman_package_files.rb.txt](https://github.com/oneclick/rubyinstaller2/files/1183615/pacman_package_files.rb.txt)

**Comment by MSP-Greg** [comment]
Just got back to the issue, looks like pacman -Qi needs to be done to find package dependencies.

BTW, added RI2 to my docs site, see [here](https://msp-greg.github.io/ri2/index.html).  Wiki pages in docs lists.

**Comment by MSP-Greg** [comment]
I drastically changed the code, as pacman calls are rather expensive.  It also follows the dependencies chain.  Since my build system works with a git repo, and I prefer as little duplication (or version specific code) as possible, I'm now using  the code to determine the dll's to include in a build.

I've attached output of test code ([pkg_dll_depends.txt](https://github.com/oneclick/rubyinstaller2/files/1185773/pkg_dll_depends.txt)), it shows dll dependencies of package arrays based on package info.

I suspect several of the dll's are used by package .exe files like openssl.exe or sqlite3.exe, but I'm not that concerned about a few megs more of dll's.  In some respects, if the exe files can be made to run off of the built in dll's, they might be helpful to have included in a Ruby build.

Now, my build system doesn't require any code or assumptions to check for issues like what version of OpenSSL is being used, and hence, what dll's to include (1.1.0 uses different file names than 1.0.2.)

Given that you're involved with security issues, I thought it interesting that the OpenSSL package lists pkcs11 lib files.

As one using the MSYS2/MinGW system for building & testing with various package versions, decoupling it from my 'daily use' ruby install would be helpful...

If you're not interested in this, feel free to close.

**Comment by larskanis** [comment]
Hi @MSP-Greg ! Thank you for testing and sharing your ideas.

We already support both - MSYS2 installed into system path `C:/msys64` and into per-Ruby path `C:/Ruby24-x64/msys64`. It is therefore easy to install several ruby environments with their own installed packages. They are fully independent to each other. See also https://github.com/oneclick/rubyinstaller2/issues/58 .

Copying DLLs around is no reliable generic option. Packages like imagemagick install a whole bunch of DLLs and config files into several directories, which are expected to be available at the given path at runtime. So we would need to preserve the directory structure of each package. Also package maintainers don't expect to get their package files disrupted, so that this situation isn't tested anywhere. But when installing whole packages, this isn't very different to running per-Ruby MSYS2 environments.

Note, that this is different for the builtin DLLs. They are taken out of particular packages, but it only a very limited set of files and we make sure that they work as expected by our tests. It's not a generic mechanism that works for each and every DLL/package.

Regarding the OpenSSL DLL version issue, I opened a separate issue: https://github.com/oneclick/rubyinstaller2/issues/60

**Comment by larskanis** [comment]
@MSP-Greg Also note, that `ridk enable` always enables the MSYS2 installation, which is found first. Therefore a per-Ruby MSYS2 is preferred to a system MSYS2.
