### ISSUE TITLE
Safe to upgrade to a newer version?

### ISSUE THREAD

**Issue by OuSatoru** [oneclick/rubyinstaller2#82]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
**Is it safe to install a newer version directly to the original folder without uninstalling? if to update ruby version with gems**

## Steps to reproduce
--

## What's the output from `ridk version`?
ruby:
  path: D:/Lang/Ruby24-x64
  version: 2.4.2
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.2-2
  git_commit: a1b07ad
msys2:
  path: D:\Lang\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 7.2.0
os: Microsoft Windows [版本 10.0.15063]

**Comment by larskanis** [comment]
> Is it safe to install a newer version directly to the original folder without uninstalling? if to update ruby version with gems

Yes, it is safe to install directly over an old installation, when it is based on the same ruby-2.x branch. It is also safe to uninstall ruby and install the new version in the old directory. Uninstall before install will be done when installing a new version of the same Ruby-2.x branch since [this commit](https://github.com/oneclick/rubyinstaller2/commit/f50e16208e5400b4f6b5af1689f969d4c9f907e7). Uninstalling Ruby will only remove bundled or default gems which comes with RubyInstaller, but will not remove gems installed subsequently.

Please note however: it is not safe to install a ruby-2.4 on top of a ruby-2.3 version. That will probably not work, because gems needs to be re-compiled.
