### ISSUE TITLE
Can consider to use WSL on windows 10 instead of MSYS2?

### ISSUE THREAD

**Issue by OuSatoru** [oneclick/rubyinstaller2#90]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
use wsl

**Comment by larskanis** [comment]
You can use WSL with Ruby for Linux instead of MSYS2 and Ruby for Windows. The Linux stack often runs more carefree. But in WSL you're limited to filesystem and network access only. This is usually enough for web application development, but not suitable if you want to access USB devices or GPU/OpenGL/DirectX, connect to OLE components, want to call custom DLLs or run GUI applications easily. In this case you must use native Windows programs or switch entirely to Linux.

Mixing both technologies doesn't work. They can not be combined in one process, because of the different address layout, different call conventions and very different system calls. So we can not link to linux shared objects (ELF) from a Ruby process running in the WinAPI subsystem. However this is what we do when linking to mingw-w64 packages as described in the [README](https://github.com/oneclick/rubyinstaller2/blob/master/README.md#install-gems-with-c-extensions-and-additional-library-dependencies).

Using WSL for bash and co. only, will suffer from the same issues that MSYS2 has: different filesystem paths (`/c/Program Files` in bash, `C:/Program Files` in ruby), different escaping rules, different environment variables and so on. So that I don't see an advantage to mix them both.

How do you think WSL could benefit Ruby for Windows?

**Comment by OuSatoru** [comment]
Thank you

**Comment by yashpalgoyal1304** [comment]
WSL feels like this overhyped thing MS made just to have it's name and repair its in media and devs eyes.
